# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='/', max_length=500),
        ),
    ]
