# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160208_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bla',
            field=models.CharField(default='blabla', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
