# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20160211_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
