# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20160211_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialvideos',
            options={'ordering': ('my_order',)},
        ),
        migrations.AddField(
            model_name='tutorialvideos',
            name='my_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
