# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20160211_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_type',
        ),
    ]
