# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_video_video_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialvideos',
            options={},
        ),
        migrations.RemoveField(
            model_name='tutorialvideos',
            name='my_order',
        ),
    ]
