# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160130_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
