# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
